#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# Global settings
yabai -m config mouse_follows_focus		off
yabai -m config focus_follows_mouse		autoraise
yabai -m config window_origin_display		default
yabai -m config window_placement		second_child
yabai -m config window_shadow			on
yabai -m config window_opacity               	off
yabai -m config window_opacity_duration      	0.25
yabai -m config window_animation_duration    	0.0
yabai -m config active_window_opacity        	1.0
yabai -m config normal_window_opacity        	0.80
yabai -m config insert_feedback_color        	0xffd75f5f
yabai -m config split_ratio			0.50
yabai -m config split_type                   	auto
yabai -m config auto_balance                 	off
yabai -m config mouse_modifier               	fn
yabai -m config mouse_action1                	move
yabai -m config mouse_action2                	resize
yabai -m config mouse_drop_action            	swap

# general space settings
yabai -m config layout                       	bsp
yabai -m config top_padding                  	8
yabai -m config bottom_padding               	8
yabai -m config left_padding                 	8
yabai -m config right_padding                	8
yabai -m config window_gap                   	8

# other settings
yabai -m config window_zoom_persist		on
yabai -m config window_animation_frame_rate  	120

# float settings windows
yabai -m rule --add app='Finder' manage=off sticky=off
yabai -m rule --add title='Settings$' manage=off sticky=on 
yabai -m rule --add app="System Preferences" manage=off 
yabai -m rule --add app="System Settings" manage=off 
yabai -m rule --add app="System Information" manage=off 
yabai -m rule --add title="Preferences" manage=off
yabai -m rule --add title="Digital Colour Meter" manage=off 
yabai -m rule --add title="^General.*" manage=off   # Calendar settings
yabai -m rule --add title="Disk Utility" manage=off   # MacOS Disk utility
yabai -m rule --add app="App Store" manage=off   # MacOS App Store
yabai -m rule --add app="Notes" manage=off   # Apple Notes

# PyCharm windows settings
yabai -m rule --add title="Rename" manage=off
yabai -m rule --add title="Delete" manage=off
yabai -m rule --add title="Move" manage=off
yabai -m rule --add title="Copy" manage=off
yabai -m rule --add title="Evaluate" manage=off
yabai -m rule --add title="Welcome to PyCharm" manage=off
yabai -m rule --add title="^Run/Debug Configurations.*" manage=off

# Set padding for spacebar
yabai -m config external_bar all:0:30

# Focus window to mouse when windows/application is destroyed
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

echo "yabai configuration loaded.."
