#!/bin/sh
alias dotfiles="/usr/bin/git --git-dir=$HOME/Code/dotfiles/ --work-tree=$HOME"
alias cf="cd $XDG_CONFIG_HOME && ls -A"
alias cfz="nvim $XDG_CONFIG_HOME/zsh/.zshrc"
alias cfp="nvim $HOME/.zprofile"
alias cfn="nvim $XDG_CONFIG_HOME/nvim/init.lua"
alias cfac="nvim $XDG_CONFIG_HOME/aliasrc"
alias cfsc="nvim $XDG_CONFIG_HOME/shortcutrc"
