#!/bin/sh
alias cfz="nvim $XDG_CONFIG_HOME/zsh/.zshrc"
alias cfp="nvim $HOME/.zprofile"
alias cft="nvim $XDG_CONFIG_HOME/tmux/tmux.conf"
alias cfn="nvim $XDG_CONFIG_HOME/nvim/init.lua"
alias cfac="nvim $XDG_CONFIG_HOME/aliasrc"
alias cfsc="nvim $XDG_CONFIG_HOME/shortcutrc"
